# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    hostname: veiculo-postgres
    container_name: veiculo-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
      
  redis:
    image: redis:latest
    hostname: veiculo-redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local      