# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    hostname: veiculo-postgres
    container_name: veiculo-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
      
  redis:
    image: redis:6.2-alpine
    hostname: veiculo-redis
    container_name: veiculo-redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local      