micronaut:
  application:
    name: apiGateway
  server:
    port: 9090
  config-client:
    enabled: true

consul:
  client:
    registration:
      enabled: true
    defaultZone: "consul:8500"

gateway:
  services:
    - veiculo-service
    - loja-service
    - relatorio-service

netty:
  default:
    allocator:
      max-order: 3


