micronaut:
  application:
    name: lojaService
  server:
    port: -1 #-1 para subir porta aleatoria

netty:
  default:
    allocator:
      max-order: 3

kafka:
  bootstrap:
    servers: broker:9092

consul:
  client:
    registration:
      enabled: true
    defaultZone: "consul:8500"