micronaut:
  application:
    name: relatorioService
  server:
    port: 8082

netty:
  default:
    allocator:
      max-order: 3

kafka:
  bootstrap:
    servers: localhost:9092

mongodb:
  uri: 'mongodb://root:example@localhost:27017/admin?authSource=admin'
