micronaut:
  application:
    name: relatorioService
  server:
    port: -1 #-1 para subir porta aleatoria

netty:
  default:
    allocator:
      max-order: 3

kafka:
  bootstrap:
    servers: broker:9092

mongodb:
  uri: 'mongodb://root:example@relatorio-mongo:27017/admin?authSource=admin'

consul:
  client:
    registration:
      enabled: true
    defaultZone: "consul:8500"
